export const CREATE_PHOTO_INIT = 'CREATE_PHOTO_INIT'
export const CREATE_PHOTO_SUCCESS = 'CREATE_PHOTO_SUCCESS'
export const CREATE_PHOTO_FAILURE = 'CREATE_PHOTO_FAILURE'

export const FETCH_PHOTO_INIT = 'FETCH_PHOTO_INIT'
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS'
export const FETCH_PHOTO_FAILURE = 'FETCH_PHOTO_FAILURE'

export const FETCH_PHOTO_BY_ID_INIT = 'FETCH_PHOTO_BY_ID_INIT'
export const FETCH_PHOTO_BY_ID_SUCCESS = 'FETCH_PHOTO_BY_ID_SUCCESS'
export const FETCH_PHOTO_BY_ID_FAILURE = 'FETCH_PHOTO_BY_ID_FAILURE'

export const DELETE_PHOTO_BY_ID_INIT = 'DELETE_PHOTO_BY_ID_INIT'
export const DELETE_PHOTO_BY_ID_SUCCESS = 'DELETE_PHOTO_BY_ID_SUCCESS'
export const DELETE_PHOTO_BY_ID_FAILURE = 'DELETE_PHOTO_BY_ID_FAILURE'
